"""add reviews model

Revision ID: eed1cabb51f1
Revises: 
Create Date: 2017-02-22 10:01:56.014004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eed1cabb51f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('reviews', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.alter_column('reviews', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('reviews', 'user_id')
    # ### end Alembic commands ###
